### ISSUE TITLE
Red error: InternalError react-packager has encountered an internal error

### ISSUE THREAD

**Issue by jimthedev** [OssamaZ/react-native-flux-boilerplate#1]
Hello,

It is strange, the project loads up the simulator. I see the white text for a bit, then all of the sudden I get a red error and this is in my Xcode terminal.

```
2015-09-13 21:46:22.970 [warn][tid:NSOperationQueue 0x7fe7b505f790 :: NSOperation 0x7fe7b2ca9b50 (QOS: UTILITY)][RCTDevMenu.m:211] RCTSourceCode module scriptURL has not been set

2015-09-13 21:46:22.987 [error][tid:NSOperationQueue 0x7fe7b505f790 :: NSOperation 0x7fe7b2ca9b50 (QOS: UTILITY)][RCTBatchedBridge.m:127] Error Domain=JSServer Code=500 "{&quot;type&quot;:&quot;InternalError&quot;,&quot;message&quot;:&quot;react-packager has encountered an internal error, please check your terminal error output for more details&quot;}
" UserInfo=0x7fe7b2c40c20 {NSLocalizedDescription={&quot;type&quot;:&quot;InternalError&quot;,&quot;message&quot;:&quot;react-packager has encountered an internal error, please check your terminal error output for more details&quot;}
}
```

At the same time this is in my terminal window:

```
React packager ready.

[9:37:40 PM] <START> fs crawl
TypeError: Cannot read property 'root' of null
    at /Users/jcummins/projects/react-native-flux-boilerplate/node_modules/react-native/packager/react-packager/src/DependencyResolver/crawlers/index.js:16:84
    at tryCallOne (/Users/jcummins/projects/react-native-flux-boilerplate/node_modules/react-native/node_modules/promise/lib/core.js:37:12)
    at /Users/jcummins/projects/react-native-flux-boilerplate/node_modules/react-native/node_modules/promise/lib/core.js:103:15
    at flush (/Users/jcummins/projects/react-native-flux-boilerplate/node_modules/react-native/node_modules/promise/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)
{"type":"InternalError","message":"react-packager has encountered an internal error, please check your terminal error output for more details"}
[9:39:14 PM] <START> request:/index.ios.bundle
```

**Comment by OssamaZ** [comment]
make sure to quit the packager terminal
start the project by runing 'npm run hot'  or just 'npm start' for runing the app without the hot load.

you should see React packager ready in your terminal, then you can execute the project from Xcode.

**Comment by jimthedev** [comment]
I did the following:
1. Killed packager and closed the terminal window with packager in it.
2. Run Application.xcodeproj in Xcode
3. I've tried Node v0.12, IOJS 2, Node 4.
4. I also tried not using the hotloader and just using `npm start`
   Still getting the same error.

```
[08:57:41] <START> fs crawl
TypeError: Cannot read property 'root' of null
    at /Users/jcummins/projects/react-native-flux-boilerplate/node_modules/react-native/packager/react-packager/src/DependencyResolver/crawlers/index.js:16:84
    at tryCallOne (/Users/jcummins/projects/react-native-flux-boilerplate/node_modules/react-native/node_modules/promise/lib/core.js:37:12)
    at /Users/jcummins/projects/react-native-flux-boilerplate/node_modules/react-native/node_modules/promise/lib/core.js:103:15
    at flush (/Users/jcummins/projects/react-native-flux-boilerplate/node_modules/react-native/node_modules/promise/node_modules/asap/raw.js:50:29)
    at process._tickCallback (node.js:337:11)
{"type":"InternalError","message":"react-packager has encountered an internal error, please check your terminal error output for more details"}
[08:58:00] <START> request:/index.ios.bundle
[08:58:00] <START> find dependencies
```

**Comment by OssamaZ** [comment]
to run the project you need to start the webpack dev server from the command line,
- open the terminal and cd to the root of your project,
- npm run hot (when the _React packager ready_. message is shown) then you can pass to Xcode to run the simulator.
  see the issues section in the readme file if you had any trouble at this stage.

**Comment by OssamaZ** [comment]
The problem here is that the react native default packager looks for an index.ios file in the root directory of your project, if it doesn't find it, it can't load you project.
In our case, the index.io file is served automatically by webpack, se we need to make sure the webpack dev server is running before executing the app from Xcode.

**Comment by OssamaZ** [comment]
Closing the issue.
